import { flattenMergeRegions, mergeThreeWay, splitLines } from '../../common/index';

/** Save candidate. */
export interface SaveCandidate {
  /** Full document text to write to the file (LF). */
  readonly text: string;
  /**
   * Whether at least one conflict region was found.
   *
   * A separate feature unit provides the UI for choosing and resolving conflicts. This value is only an integration
   * point here and does not affect whether the candidate can be saved.
   */
  readonly hasConflict: boolean;
}

/**
 * Combines source and view changes into one save candidate using the merge base as their common ancestor.
 *
 * A conflict region omits the base lines and places the view lines immediately after the source lines. Git-style
 * markers are not added because they would break the HTML. Until the resolution UI is available, preserving both
 * versions takes priority.
 *
 * All three inputs must already be normalized to LF. The caller performs normalization so line-ending-only
 * differences do not become changed regions.
 *
 * @param baseText Full document text of the common ancestor (LF).
 * @param sourceText Full text of the current clean source (LF).
 * @param viewText Full text generated by the view after input was blocked (LF).
 * @returns The full save candidate text and whether it contains a conflict.
 */
export function mergeSaveCandidate(
  baseText: string,
  sourceText: string,
  viewText: string,
): SaveCandidate {
  const merged = mergeThreeWay(splitLines(baseText), splitLines(sourceText), splitLines(viewText));

  // Flattening is left to the common layer. Writing it separately for save and history would order the same
  // conflict differently depending on the path.
  return { text: flattenMergeRegions(merged.regions), hasConflict: merged.hasConflict };
}
