import { CONFLICT_CHOICE, flattenMergeRegions, mergeThreeWay, splitLines } from '../../common/index';
import type { ConflictChoice, MergeRegion, MergeResult } from '../../common/index';

/** Save candidate. */
export interface SaveCandidate {
  /** Full document text to write to the file (LF). */
  readonly text: string;
  /**
   * Whether at least one conflict region was found.
   *
   * The candidate text keeps both sides of every conflict region. A save asks the user to choose instead, so it uses
   * the regions directly; this value serves the paths that keep both sides.
   */
  readonly hasConflict: boolean;
}

/**
 * Combines source and view changes into one save candidate using the merge base as their common ancestor.
 *
 * A conflict region omits the base lines and places the view lines immediately after the source lines. Git-style
 * markers are not added because they would break the HTML. A save asks the user to choose instead; the restore and
 * recovery paths use this function and keep both versions so that neither is dropped without the user knowing.
 *
 * All three inputs must already be normalized to LF. The caller performs normalization so line-ending-only
 * differences do not become changed regions.
 *
 * @param baseText Full document text of the common ancestor (LF).
 * @param sourceText Full text of the current clean source (LF).
 * @param viewText Full text generated by the view after input was blocked (LF).
 * @returns The full save candidate text and whether it contains a conflict.
 */
export function mergeSaveCandidate(
  baseText: string,
  sourceText: string,
  viewText: string,
): SaveCandidate {
  const merged = mergeSaveRegions(baseText, sourceText, viewText);

  // Flattening is left to the common layer. Writing it separately for save and history would order the same
  // conflict differently depending on the path.
  return { text: flattenMergeRegions(merged.regions), hasConflict: merged.hasConflict };
}

/**
 * Merges source and view changes without flattening, so that the user can choose a side for each conflict region.
 *
 * All three inputs must already be normalized to LF.
 *
 * @param baseText Full document text of the common ancestor (LF).
 * @param sourceText Full text of the current clean source (LF).
 * @param viewText Full text generated by the view after input was blocked (LF).
 * @returns The merge regions in document order and whether any conflict exists.
 */
export function mergeSaveRegions(baseText: string, sourceText: string, viewText: string): MergeResult {
  return mergeThreeWay(splitLines(baseText), splitLines(sourceText), splitLines(viewText));
}

/**
 * Builds the full save candidate text from merge regions and the side chosen for each conflict region.
 *
 * @param regions Merge regions returned by the save merge.
 * @param choices The choice for each conflict region, in document order.
 * @returns The full document text to save (LF).
 * @throws {RangeError} When the number of choices differs from the number of conflict regions.
 */
export function flattenSaveCandidate(
  regions: readonly MergeRegion[],
  choices: readonly ConflictChoice[],
): string {
  return flattenMergeRegions(regions, choices);
}

/**
 * Merges source and view changes like a save and keeps the view side of every conflict region.
 *
 * This is what the save would write had the user kept the visual editor's version everywhere. Undoing a choice
 * returns here rather than to the view output, so that source changes merged on other lines by the same save stay.
 *
 * All three inputs must already be normalized to LF.
 *
 * @param baseText Full document text of the common ancestor (LF).
 * @param sourceText Full text of the current clean source (LF).
 * @param viewText Full text generated by the view after input was blocked (LF).
 * @returns The full document text with the view side kept in every conflict region (LF).
 */
export function mergeViewSide(baseText: string, sourceText: string, viewText: string): string {
  const regions = mergeSaveRegions(baseText, sourceText, viewText).regions;
  const choices = regions.filter((region) => region.kind === 'conflict').map(() => CONFLICT_CHOICE.view);
  return flattenSaveCandidate(regions, choices);
}
